CREATE DATABASE Retail_Brazilian_DB;

USE DATABASE Retail_Brazilian_DB;

CREATE OR REPLACE SCHEMA Retail_Brazilian_SCHEMA;

USE SCHEMA Retail_Brazilian_SCHEMA;


CREATE WAREHOUSE Retail_Brazilian_WH
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE Retail_Brazilian_WH;
